// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYuuRlqT_zbATTgDe9crDe8yJnnV0Pxg',
    appId: '1:184904692444:web:d16647bce2ac312f32ba19',
    messagingSenderId: '184904692444',
    projectId: 'trabalhosprint',
    authDomain: 'trabalhosprint.firebaseapp.com',
    storageBucket: 'trabalhosprint.firebasestorage.app',
    measurementId: 'G-PP9YET6GL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtXcdJvwrynfrhOw1YGSD19CFisMVs_k',
    appId: '1:184904692444:android:2f892dd09e8a30fb32ba19',
    messagingSenderId: '184904692444',
    projectId: 'trabalhosprint',
    storageBucket: 'trabalhosprint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxr7-X8N1oVY7x0mzsi8gjh1ZMhXuO6fE',
    appId: '1:184904692444:ios:5b5251d441e2ad9832ba19',
    messagingSenderId: '184904692444',
    projectId: 'trabalhosprint',
    storageBucket: 'trabalhosprint.firebasestorage.app',
    iosBundleId: 'com.example.sprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxr7-X8N1oVY7x0mzsi8gjh1ZMhXuO6fE',
    appId: '1:184904692444:ios:5b5251d441e2ad9832ba19',
    messagingSenderId: '184904692444',
    projectId: 'trabalhosprint',
    storageBucket: 'trabalhosprint.firebasestorage.app',
    iosBundleId: 'com.example.sprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIYuuRlqT_zbATTgDe9crDe8yJnnV0Pxg',
    appId: '1:184904692444:web:0071973886c266eb32ba19',
    messagingSenderId: '184904692444',
    projectId: 'trabalhosprint',
    authDomain: 'trabalhosprint.firebaseapp.com',
    storageBucket: 'trabalhosprint.firebasestorage.app',
    measurementId: 'G-32MLWC7PQV',
  );
}
